### PR TITLE
fixed typos

### PR DESCRIPTION
**Pull request by syncikin**

### CODE REVIEW

**Comment by syncikin** [comment]
The failing tests are due to the output report changing.

**Comment by birdofpreyru** [comment]
@syncikin ok, can you update expected inputs, please?

**Comment by birdofpreyru** [comment]
https://github.com/ConsenSys/mythril/wiki/Running-Tests#run-the-tests

**Comment by syncikin** [comment]
@birdofpreyru oops, missed this, they've been updated now.

**Comment by b-mueller** [comment]
Thanks @syncikin!

**Pull request merged**
