### PR TITLE
Use newer z3 version

### PR DESCRIPTION
**Pull request by b-mueller**

### CODE REVIEW

**Comment by b-mueller** [comment]
Solves the issue where Z3 ignores execution timeout. Further helps saving #931.

**Comment by norhh** [comment]
I think our release of z3 doesn't have a problem with BECToken.sol, Thats happens to be my regular testing contract these days and I haven't had a problem with it.

**Comment by b-mueller** [comment]
> I think our release of z3 doesn't have a problem with BECToken.sol, That happens to be my regular testing contract these days and I haven't had a problem with it for that span

Really? That's weird, whenever I ran Mythril on BECToken.sol with any Solver timeout longer than a few seconds Z3 would get stuck on some task for several minutes. In never got it to get proper coverage or detect the MUL overflow within a reasonable time. With the new version, I detect it reliably with `-t1 --execution-timeout 90`.

Could be a Mac-related problem...

**Comment by norhh** [comment]
The older z3 should be uninstalled, else that version would be used. That might be the reason.

**Pull request merged**
