### PR TITLE
added Dockerfile

### PR DESCRIPTION
**Pull request by thec00n**

### CODE REVIEW

**Comment by b-mueller** [comment]
Should we use this instead of the [existing Dockerfile](https://github.com/ConsenSys/mythril/blob/master/Dockerfile)?

**Comment by thec00n** [comment]
I did not see that there was already one in the master. Disregard, it's pretty much the same.

**Comment by b-mueller** [comment]
ok cool, thx!

**Comment by b-mueller** [comment]
Reopening this as there seem to be [issues with the current Dockerfile](https://github.com/ConsenSys/mythril/issues/65).

**Pull request closed without merging**
