### PR TITLE
Adds tox testing

### PR DESCRIPTION
**Pull request by joshuata**

### CODE REVIEW

**Comment by joshuata** [comment]
I'm seeing an interesting problem: tests fail under python 3.5, but not 3.6.

**Comment by joshuata** [comment]
I have decided to temporarily disable python 3.5 testing while we fix issue #245. We can add the other versions in once the problematic test (test_get_source_info_without_name_gets_latest_contract_info ) has been fixed. The detailed failure can be [found here](https://circleci.com/gh/ConsenSys/mythril/300#tests/containers/0)

**Comment by b-mueller** [comment]
@birdofpreyru can you please take a look at this.

**Comment by birdofpreyru** [comment]
@joshuata it seems to break our integration tests.

**Comment by joshuata** [comment]
@birdofpreyru Unless the integration tests are run separately, I'm seeing the same behavior other places, for example with with #229 [tests](https://circleci.com/gh/ConsenSys/mythril/271?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link).

**Comment by birdofpreyru** [comment]
@joshuata what behavior exactly?

**Comment by joshuata** [comment]
Nevermind. I was assuming they were supposed to run in CI, so I was seeing that they had never run and assumed that was the bug.

**Comment by birdofpreyru** [comment]
@joshuata try this, to see the problem that crushes integration tests:

1. In your code replace CircleCI config by
```
defaults: &defaults
  docker:
    - image: birdofpreyru/mythril-integration-tests:0.0.3

version: 2
jobs:
  # Basic testing of a new commit to any branch.
  test:
    <<: *defaults
    steps:
      - checkout:
          path: /home/mythril

      # Uncomment, for local testing with circleci command, as it ignores
      # path param in checkout command, and this symlink compenstates for that.
      - run: ln -s /root/project /home/mythril

      - restore-cache:
          keys:
            - tox-env-{{ checksum "/home/mythril/setup.py" }}

      - run:
          name: Installing mythril tools
          command: ./install-mythril-tools.sh laser-ethereum
          working_directory: /home

      - run:
          name: Install tox envs
          command: tox -vv --notest
          working_directory: /home/mythril
          environment:
            LC_ALL: C.UTF-8
            LANG: C.UTF-8

      - save_cache:
          key: tox-env-{{ checksum "/home/mythril/setup.py" }}
          paths: 
            - .tox/py*
            - /root/.cache/pip/wheels/

      - run:
          background: true
          name: Launch of background geth instance
          command: geth --syncmode full --rpc --shh

      - run:
          name: Unit-testing
          command: tox
          working_directory: /home/mythril
          environment:
            LC_ALL: C.UTF-8
            LANG: C.UTF-8

      - store_test_results:
          path: /home/mythril/.tox/output

      - store_artifacts:
          path: /home/mythril/.tox/output

      - run:
          name: Ensuring that setup script is functional
          command: python3 setup.py install
          working_directory: /home/mythril

      - run:
          name: TMP TEST
          command: myth -xc 60606040526004361061006c576000357c0100000000000000000000000000000000000000000000000000000000900463ffffffff168062362a951461006e57806327e235e31461009c5780632e1a7d4d146100e957806370a082311461010c5780638529587714610159575b005b61009a600480803573ffffffffffffffffffffffffffffffffffffffff169060200190919050506101ae565b005b34156100a757600080fd5b6100d3600480803573ffffffffffffffffffffffffffffffffffffffff169060200190919050506101fd565b6040518082815260200191505060405180910390f35b34156100f457600080fd5b61010a6004808035906020019091905050610215565b005b341561011757600080fd5b610143600480803573ffffffffffffffffffffffffffffffffffffffff1690602001909190505061033e565b6040518082815260200191505060405180910390f35b341561016457600080fd5b61016c610386565b604051808273ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200191505060405180910390f35b346000808373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff1681526020019081526020016000206000828254019250508190555050565b60006020528060005260406000206000915090505481565b806000803373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff168152602001908152602001600020541015156102da573373ffffffffffffffffffffffffffffffffffffffff168160405160006040518083038185876187965a03f19250505050806000803373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff168152602001908152602001600020600082825403925050819055505b600160009054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff166001604051808260ff16815260200191505060006040518083038160008661646e5a03f19150505050565b60008060008373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff168152602001908152602001600020549050919050565b600160009054906101000a900473ffffffffffffffffffffffffffffffffffffffff16815600a165627a7a7230582064223a1082bfbb3bb4a508b17a422e90fced0582c3905e1bfbf384e91f6ac7d40029

  deploy:
    <<: *defaults
    steps:
      - checkout:
          path: /home/mythril
      - run:
          name: Verify Git tag vs. version
          command: python3 setup.py verify
          working_directory: /home/mythril
      - run:
          name: Build
          command: python3 setup.py sdist
          working_directory: /home/mythril
      - run:
          name: Deploy
          command: twine upload dist/*
          working_directory: /home/mythril

workflows:
  version: 2
  build:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
      - deploy:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
          requires:
            - test

```

2. Exectute the build locally it as `$ sudo circleci build --job test`

You will see that the last command, which I put into this script instead of the integration tests, will fail.

**Comment by birdofpreyru** [comment]
The actual error reads:
```
  #!/bin/bash -eo pipefail
myth -xc 60606040526004361061006c576000357c0100000000000000000000000000000000000000000000000000000000900463ffffffff168062362a951461006e57806327e235e31461009c5780632e1a7d4d146100e957806370a082311461010c5780638529587714610159575b005b61009a600480803573ffffffffffffffffffffffffffffffffffffffff169060200190919050506101ae565b005b34156100a757600080fd5b6100d3600480803573ffffffffffffffffffffffffffffffffffffffff169060200190919050506101fd565b6040518082815260200191505060405180910390f35b34156100f457600080fd5b61010a6004808035906020019091905050610215565b005b341561011757600080fd5b610143600480803573ffffffffffffffffffffffffffffffffffffffff1690602001909190505061033e565b6040518082815260200191505060405180910390f35b341561016457600080fd5b61016c610386565b604051808273ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200191505060405180910390f35b346000808373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff1681526020019081526020016000206000828254019250508190555050565b60006020528060005260406000206000915090505481565b806000803373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff168152602001908152602001600020541015156102da573373ffffffffffffffffffffffffffffffffffffffff168160405160006040518083038185876187965a03f19250505050806000803373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff168152602001908152602001600020600082825403925050819055505b600160009054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff166001604051808260ff16815260200191505060006040518083038160008661646e5a03f19150505050565b60008060008373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff168152602001908152602001600020549050919050565b600160009054906101000a900473ffffffffffffffffffffffffffffffffffffffff16815600a165627a7a7230582064223a1082bfbb3bb4a508b17a422e90fced0582c3905e1bfbf384e91f6ac7d40029
Traceback (most recent call last):
  File "/usr/local/bin/myth", line 4, in <module>
    __import__('pkg_resources').run_script('mythril==0.17.14', 'myth')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 742, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1503, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.17.14-py3.6.egg/EGG-INFO/scripts/myth", line 9, in <module>
    mythril.interfaces.cli.main()
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.17.14-py3.6.egg/mythril/interfaces/cli.py", line 202, in main
    max_depth=args.max_depth)
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.17.14-py3.6.egg/mythril/mythril.py", line 325, in fire_lasers
    issues = fire_lasers(sym, modules)
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.17.14-py3.6.egg/mythril/analysis/security.py", line 20, in fire_lasers
    issues += module.execute(statespace)
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.17.14-py3.6.egg/mythril/analysis/modules/call_to_dynamic_with_gas.py", line 51, in execute
    func = statespace.find_storage_write(index)
TypeError: find_storage_write() missing 1 required positional argument: 'index'
```

**Comment by joshuata** [comment]
It still works perfectly for me. I wonder if installing the mythril-api repo is somehow clobbering source files from mythril.

**Comment by birdofpreyru** [comment]
@joshuata ok, weirdly enough, it still does not work for me locally, but indeed works in the remote CircleCI. Something wrong with my local setup :( Sorry about it! I have merged your changes to **master**.

**Pull request merged**
