### PR TITLE
Fix myth --version typo in docs

### PR DESCRIPTION
**Pull request by sirhashalot**

### CODE REVIEW

**Comment by norhh** [comment]
@sirhashalot, thanks for the contribution, can you push the changes to `develop` over `master`?

**Review by norhh — APPROVED** [review]
👍

**Comment by norhh** [comment]
@ sirhashalot  can you sign the CLA?

**Comment by sirhashalot** [comment]
At some point the CONTRIBUTING.md file should be updated to include these steps

**Pull request merged**
