### PR TITLE
Handle concrete hashes

### PR DESCRIPTION
**Pull request by norhh**

### CODE REVIEW

**Comment by b-mueller** [comment]
For some reason the exception that previously had a wrong example is not detected at all with this patch. 

**Result with Mythril v0.21.23:**

```
$ myth analyze pwnable.sol:VerifyPwnable -mexceptions
==== Exception State ====
SWC ID: 110
Severity: Low
Contract: VerifyPwnable
Function name: UpdateBonusCodeAt(uint256,uint256)
PC address: 454
Estimated Gas Usage: 8737 - 29587
A reachable exception has been detected.
It is possible to trigger an exception (opcode 0xfe). Exceptions can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. Note that explicit `assert()` should only be used to check invariants. Use `require()` for regular input checking.
--------------------
In file: pwnable.sol:35

assert(msg.sender == old_owner || owner == old_owner)

--------------------
Initial State:

Account: [CREATOR], balance: 0x100029e2ecf21bb80, nonce:0, storage:{}
Account: [ATTACKER], balance: 0x0, nonce:0, storage:{}
Account: [SOMEGUY], balance: 0x43400180000020100, nonce:0, storage:{}

Transaction Sequence:

Caller: [CREATOR], calldata: , value: 0x0
Caller: [CREATOR], function: PopBonusCode(), txdata: 0x7adde4ef, value: 0x0
Caller: [SOMEGUY], function: UpdateBonusCodeAt(uint256,uint256), txdata: 0x4f798da7000000000000000000000000000004a0b88080808080808080808000000000000000000000000000000000000000000000000000000000000000000000000000, value: 0x0
```

--> This decodes to:

```
PopBonusCode()
UpdateBonusCodeAt(403139567605942861219021332510708982611968,0)
```

**Result with this branch:**

```
 $MYTH analyze pwnable.sol:VerifyPwnable -mexceptions 
The analysis was completed successfully. No issues were detected.
```

**Expected:**

```
PopBonusCode()
UpdateBonusCodeAt(35707666377435648211887908874984608119992236509074197713628505308453184860938,0)
```

**Comment by norhh** [comment]
Can you send me the code for it?

**Comment by b-mueller** [comment]
Ooops yeah:

```
pragma solidity ^0.5.0;

contract Pwnable {
    address public owner;
    uint[] private bonusCodes;
    
    constructor() public {
        bonusCodes = new uint[](0);
        owner = msg.sender;
    }
    
    function PushBonusCode(uint c) public {
        bonusCodes.push(c);
    }
    
    function PopBonusCode() public {
        require(0 <= bonusCodes.length);
        bonusCodes.length--;
    }
    
    function UpdateBonusCodeAt(uint idx, uint c) public {
        require(idx < bonusCodes.length);
        bonusCodes[idx] = c;
    }
    
}

contract VerifyPwnable is Pwnable {

	modifier checkInvariants {
        address old_owner = owner;

		_;

		assert(msg.sender == old_owner || owner == old_owner);
	}
    
     function PushBonusCode(uint c) public checkInvariants {
         super.PushBonusCode(c);
     }

    function PopBonusCode() public checkInvariants {
        super.PopBonusCode();
    }

    function UpdateBonusCodeAt(uint idx, uint c) public checkInvariants {
        super.UpdateBonusCodeAt(idx, c);
    }

}
```

**Comment by b-mueller** [comment]
I'm getting the same results for the simplified example:

```
pragma solidity ^0.5.0;

contract HashTest {
    function test(uint value) public pure {
        bytes32 hash = keccak256("\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01");
        uint256 num = uint256(hash);
        // num == 80084422859880547211683076133703299733277748156566366325829078699459944778998
        // MythX gets this right
        assert(num + value != 0);
        // Correct solution: num == 35707666377435648211887908874984608119992236509074197713628505308453184860938
        // MythX / Mythril output: 
        // Counterexample 1: 403139567605942861219021332510708982611968  --> WRONG
        // Counterexample 2: 35707666377435648211887908874984608119992236509074197713628505308453184860938 -> CORRECT
    }
}
```

```
$ $MYTH analyze hashtest.sol -mexceptions
The analysis was completed successfully. No issues were detected.

(mythril) Bernhards-MacBook-Pro:Desktop bernhardmueller$ 
```

**Comment by norhh** [comment]
Something's wrong with the develop. Before the merge commit it detects everything.

**Comment by b-mueller** [comment]
Hmm caused by the new module architecture then? The benchmarks on develop look fine though

**Comment by norhh** [comment]
yes, removing the `-m exceptions` seems to make it work. something's wrong with loading whitelisted modules.

**Comment by norhh** [comment]
with respect to the new analysis module usage, it's `myth a file.sol -m "Reachable Exceptions"` .
We should specify the title rather than the file name.

**Comment by b-mueller** [comment]
Cool, let's merge this then and add a check later that errors when the the
-m list contains an invalid module name (this has been on my todo list for
a while anyway)

**Pull request merged**
