### PR TITLE
Bugfix 314

### LINKED ISSUE #309: Stack assertion error when running on -l flag
**Describe the bug**
Integer overflow analysis terminates with assertion error when run on dynamic link.Problem may be in some 'CALL' related areas as not using -l won't result in this problem

**To Reproduce**
steps to reproduce the behavior.
```
>python3 ./myth -xila 0x869ed845F8D4B436fFE778ADC0E9ab253E53f0F2
Traceback (most recent call last):
  File "./myth", line 9, in <module>
    mythril.interfaces.cli.main()
  File "/home/nikhil/MYTHRIL/mythril/mythril/interfaces/cli.py", line 198, in main
    max_depth=args.max_depth)
  File "/home/nikhil/MYTHRIL/mythril/mythril/mythril.py", line 345, in fire_lasers
    issues = fire_lasers(sym, modules)
  File "/home/nikhil/MYTHRIL/mythril/mythril/analysis/security.py", line 20, in fire_lasers
    issues += module.execute(statespace)
  File "/home/nikhil/MYTHRIL/mythril/mythril/analysis/modules/integer.py", line 34, in execute
    issues += _check_integer_overflow(statespace, state, node)
  File "/home/nikhil/MYTHRIL/mythril/mythril/analysis/modules/integer.py", line 84, in _check_integer_overflow
    if not _verify_integer_overflow(statespace, node, expr, state, model, constraint, op0, op1):
  File "/home/nikhil/MYTHRIL/mythril/mythril/analysis/modules/integer.py", line 103, in _verify_integer_overflow
    interesting_usages = _search_children(statespace, node, expr, constraint=[constraint], index=node.states.index(state))
  File "/home/nikhil/MYTHRIL/mythril/mythril/analysis/modules/integer.py", line 234, in _search_children
    taint_result = TaintRunner.execute(statespace, node, state, initial_stack=taint_stack)
  File "/home/nikhil/MYTHRIL/mythril/mythril/laser/ethereum/taint_analysis.py", line 106, in execute
    records = TaintRunner.execute_node(node, record, index)
  File "/home/nikhil/MYTHRIL/mythril/mythril/laser/ethereum/taint_analysis.py", line 126, in execute_node
    records.append(TaintRunner.execute_state(records[-1], current_state))
  File "/home/nikhil/MYTHRIL/mythril/mythril/laser/ethereum/taint_analysis.py", line 131, in execute_state
    assert len(state.mstate.stack) == len(record.stack)
AssertionError
```

**Expected behavior**
There should not be an assertion error

**Desktop (please complete the following information):**
Ubuntu-17.10

### LINKED ISSUE #314: Stack Underflow Exception is thrown for some contracts.
**Describe the bug**
Stack Underflow Exception is thrown for some contracts.

**To Reproduce**
```
>python3 myth -xila 0x47d4cc3d331525976553baff7c9e4d410087804a

Traceback (most recent call last):
  File "/home/nikhil/MYTHRIL/mythril/mythril/laser/ethereum/instructions.py", line 100, in pop_
    global_state.mstate.stack.pop()
IndexError: pop from empty list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "myth", line 9, in <module>
    mythril.interfaces.cli.main()
  File "/home/nikhil/MYTHRIL/mythril/mythril/interfaces/cli.py", line 198, in main
    max_depth=args.max_depth)
  File "/home/nikhil/MYTHRIL/mythril/mythril/mythril.py", line 343, in fire_lasers
    max_depth=max_depth)
  File "/home/nikhil/MYTHRIL/mythril/mythril/analysis/symbolic.py", line 22, in __init__
    self.laser.sym_exec(address)
  File "/home/nikhil/MYTHRIL/mythril/mythril/laser/ethereum/svm.py", line 63, in sym_exec
    self._sym_exec()
  File "/home/nikhil/MYTHRIL/mythril/mythril/laser/ethereum/svm.py", line 71, in _sym_exec
    new_states, op_code = self.execute_state(global_state)
  File "/home/nikhil/MYTHRIL/mythril/mythril/laser/ethereum/svm.py", line 84, in execute_state
    return Instruction(op_code, self.dynamic_loader).evaluate(global_state), op_code
  File "/home/nikhil/MYTHRIL/mythril/mythril/laser/ethereum/instructions.py", line 69, in evaluate
    return instruction_mutator(global_state)
  File "/home/nikhil/MYTHRIL/mythril/mythril/laser/ethereum/instructions.py", line 34, in wrapper
    new_global_states = func(self, global_state_copy)
  File "/home/nikhil/MYTHRIL/mythril/mythril/laser/ethereum/instructions.py", line 102, in pop_
    raise StackUnderflowException()
mythril.laser.ethereum.instructions.StackUnderflowException

```

**Expected behavior**
It should execute properly

**Desktop (please complete the following information):**
 - Ubuntu
 - 17.10

### LINKED ISSUE #346: Error in delegatecall
## Description
Running analysis on the followin contract results in an error:
```
 0xdF7C42c18c4BAc520dd7A845AA0d85FbB87168d9
```

Two things need to be done to fix this:
 - Index error except on mload
 - delegate call fix

### PR DESCRIPTION
**Pull request by JoranHonig**
Fixes #314 

This issue was actually an indication of a much bigger problem with the execution of calls, but that has been fixed now with this pr

edit: also fixes #346
edit2: also fixes #309

### CODE REVIEW

**Comment by JoranHonig** [comment]
There still seems to be a problem with return value checking, working on it!

**Comment by JoranHonig** [comment]
Note that the taintrunner fix should be temporary ( when we start working with callbacks we'll use different taint tracking)

**Comment by norhh** [comment]
as far as i know it looks good(i don't know much), also it seems to have survived without any error for a lot of contracts(probably ~1900 contracts, which i ran to find contracts with most issues)

**Comment by JoranHonig** [comment]
@norhh Thanks for looking at it anyway, a second view of what happens is always valuable! I'll give it a once over and then merge it

**Pull request merged**
