### PR TITLE
New algo for creating loop counter keys

### PR DESCRIPTION
**Pull request by b-mueller**
Replaces the loop counter key in the bounded loops module by a checksum over the last 32 pc addresses. This is to prevent unwanted pruning when an internal function is called repeatedly.

### CODE REVIEW

**Comment by wuestholz** [comment]
@b-mueller Not sure, but maybe you want to consider fewer than the last 32 locations if those contain the current location. More concretely, assume your locations are [L0, ..., LK, ..., L31] and LK is the last location equal to L31. Then you might want to only compute the checksum based on [LK+1, ..., L31]. What do you think?

**Comment by b-mueller** [comment]
@wuestholz sounds right but I just tried it and somehow incorrect branches get pruned 😅

**Comment by wuestholz** [comment]
Hm, weird... Maybe that's related: it seems like your trace only contains the addresses. Shouldn't it contain PCs or the tuple of address and PC?

**Comment by norhh** [comment]
`Shouldn't it contain PCs or the tuples of address and PC?` is it necessary? Like there is a one to one mapping between addresses and PCs right?

**Comment by b-mueller** [comment]
>  Like there is a one to one mapping between addresses and PCs right? So wouldn't that info be redundant?

That's what I'm thinking. Checksum over the addresses should be sufficient to uniquely identify the path taken?

Loops of length n < 32 should be found after 32/n iterations. I suspect that using [LK+1, ..., L31] somehow creates the original problem where the same jump in an internal function is taken to be a loop. Not 100% sure though...

**Comment by wuestholz** [comment]
Ah, maybe I misunderstood the term "address". I assumed that it refers to the address of the contract. :)

**Comment by b-mueller** [comment]
Classic Mythril terminology!

**Comment by norhh** [comment]
`Loops of length n < 32 should be found after 32/n iterations. I suspect that using [LK+1, ..., L31] somehow creates the original problem where the same jump in an internal function is taken to be a loop.` Won't we have the same problem if loop size >32? , Loop size can easily cross 32 if there are a few array manipulations in the loop.

**Comment by b-mueller** [comment]
I think the crucial value is, if we're looking actual loops vs jumps inside a repeatedly called internal function, the distance from the start of the function to the JUMPDEST, because the path from which the function was reached should be different. Except if the function itself is being called in a loop, in that case it would be the distance to the start of the outer loop.

With a higher _n_  the risk of mistaking a JUMP inside a repeatedly called internal function for a loop decreases. However, it will take longer to identify short loops (since they have to unroll for _n/length_ iterations to generate the same key) so Mythril will overrun the user-defined bound.

Not sure what's a reasonable value here, how does 128 sound? 🙃

**Pull request closed without merging**
