### PR TITLE
Bugfix/fix fallback name

### PR DESCRIPTION
**Pull request by norhh**
remove simplifying bool in jumpi and also change fallback name.
As rocky mentioned in #390  someone using fallback as a function  it might cause a confusion. As of now i am thinking of using fallback instead of fallback() may do the work but i am not sure of it, so any suggestions?Another option as suggested by rocky is changing description of each issue for fallback seperately:- if thats the case then any suggestions on the display text for fallback.

### CODE REVIEW

**Comment by JoranHonig** [comment]
why remove the simplify?

**Comment by rocky** [comment]
> For now I'd say that just 'fallback' is fine

Using two words like "unamed fallback" will make more clear than dropping parenthesis that this is not a function name.

**Comment by norhh** [comment]
If i change it to unnamed fallback this is how it will look

**Comment by norhh** [comment]
After changing it to unnamed fallback .
```
==== Integer Overflow ====
Type: Warning
Contract: Crowdfunding
Function name: unnamed fallback
PC address: 501
A possible integer overflow exists in the function `unnamed fallback`.
The addition or multiplication may result in a value higher than the maximum representable integer.
--------------------
In file: ether_send.sol:24

balances[msg.sender] += msg.value

--------------------
```
This is fine right?

**Comment by b-mueller** [comment]
> For now I'd say that just 'fallback' is fine

I agree."fallback function" is official terminology for the code that is executed if no function hash matches. We can expect Ethereum devs to know what a fallback function is. "Unknown fallback" sounds weird.

**Comment by rocky** [comment]
It was "unnamed" not "unknown". I got that phrase from https://www.bitdegree.org/learn/solidity-fallback-functions/

> In Solidity, a contract may have precisely one unnamed function, which cannot have arguments, nor return anything.

That said, if others find "unnamed fallback" confusing , drop the "unnamed". I don't think it will be that big a deal because wrappers will have other ways to indicate what we're talking about.

**Pull request merged**
