### PR TITLE
Merge laser into mythril

### PR DESCRIPTION
**Pull request by LieutenantRoger**

### CODE REVIEW

**Comment by birdofpreyru** [comment]
@LieutenantRoger 1 test fails.

I wonder, do you have access to the test results in CircleCI?

**Comment by LieutenantRoger** [comment]
Yes, I can see the test failing detail.  The current code can pass the tests on my local, but it would fail on ci test.  

The failing test appears due to the new added test case migrated from laser-ethereum.   That test case requires to generate files on the disk.  Would it be possible due to my account privilege for generating/writing files ?

**Comment by birdofpreyru** [comment]
@LieutenantRoger still fails if I commit it to the repo as a regular branch: https://circleci.com/gh/ConsenSys/mythril/330

something wrong with the code checked by that test?

**Comment by LieutenantRoger** [comment]
[code]
FileNotFoundError: [Errno 2] No such file or directory: '/home/mythril/tests/testdata/outputs_current_laser_result/suicide.sol.json'
[/code]
It reported this error,  but this file should be generated on the fly before verifying of the tests. 

[code]
    def test_laser_result(self):
        for input_file in TESTDATA_INPUTS_CONTRACTS.iterdir():
            if input_file.name == "weak_random.sol":
                continue
            output_expected = TESTDATA_OUTPUTS_EXPECTED_LASER_RESULT / (input_file.name + ".json")
            output_current = TESTDATA_OUTPUTS_CURRENT_LASER_RESULT / (input_file.name + ".json")

            disassembly = SolidityContract(str(input_file)).disassembly
            account = svm.Account("0x0000000000000000000000000000000000000000", disassembly)
            accounts = {account.address: account}

            laser = svm.LaserEVM(accounts)
            laser.sym_exec(account.address)
            laser_info = _all_info(laser)

            output_current.write_text(json.dumps(laser_info, cls=LaserEncoder, indent=4))

            if not (output_expected.read_text() == output_expected.read_text()):
                self.found_changed_files(input_file, output_expected, output_current)

        self.assert_and_show_changed_files()
[/code]

This line is supposed to create this file on the fly
[code]
output_current.write_text(json.dumps(laser_info, cls=LaserEncoder, indent=4))
[/code]

**Comment by LieutenantRoger** [comment]
I think I may have found the problem, it's may due to another configuration file, let me update it and try again.  

Btw, I seemed can't trigger the ci test except create a new pull request. Is it due to priviledge issue, right ?

**Comment by birdofpreyru** [comment]
@LieutenantRoger I'll check the merge later tonight. 
The page, can you just prepare and send me it like markdown file(s). I'll add it to wiki myself then

**Comment by joshuata** [comment]
As I looked through I saw that you added pytest and the two extensions to `setup.py`. Since they are test scoped dependencies we should probably put them in the `tests_require` section so that we don't bloat the main package.

**Comment by birdofpreyru** [comment]
@LieutenantRoger ok, all tests work, thus I merged it in (I also moved those few test dependencies into `tests_require` section of `setup.py`). Please drop me the laser-related pages to include into wiki.

@joshuata regarding those test dependencies, should we change something else, beside just moving them to `tests_require`?

**Pull request merged**
