### PR TITLE
[WIP] Moves testing to tox

### PR DESCRIPTION
**Pull request by joshuata**
If we switch the testing program to tox we can automatically check the program against several versions of python. Eventually we could use pyenv to install several python versions in the testing environment.

### CODE REVIEW

**Comment by b-mueller** [comment]
This causes the tests on CircleCI ti fail. I don't know CircleCI well so not sure if any changes to the setup are required.

Maybe @birdofpreyru can comment on that?

**Comment by birdofpreyru** [comment]
Sure @b-mueller 

CircleCI testing / deployment happens inside Docker container created with the scripts hosted here: https://github.com/ConsenSys/mythril-ci/tree/integration-testing I guess, it should be updated in some way (installing addition Python versions there)? Wanna look into this, @joshuata, or should I handle this (hopefully, later today, but may delay for a couple of days)?

**Comment by joshuata** [comment]
I've been working on this. I should have marked that this wasn't ready for merge and I'm using it to test circleci since it works on my machine

**Comment by joshuata** [comment]
I have tried running with the local version of CircleCI, but I get an error.
```
Cannot find a job named `build` to run in the `jobs:`
```
This is apparently because workflows are [not supported for local execution](https://discuss.circleci.com/t/command-line-support-for-workflows/14510). Is it possible the problem is that I don't have access to manually execute a build step?

**Comment by birdofpreyru** [comment]
Yeap, workflows are not supported locally, but individual jobs specified in the script are. By default `$ sudo circleci build` (build here is a command, and not the job name) tried to execute *build* job, which we don't have in our config. For testing, you should run the *test* job, thus `$ sudo circleci build --job test`.

And don't forget to uncomment that line, I mentioned earlier, for local execution.

**Comment by joshuata** [comment]
Alright, I have submitted a pull request to the ci repo to add tox and pyenv to the base image. That should simplify this pull request.

**Comment by b-mueller** [comment]
Are we still going to move forward on this?

**Comment by joshuata** [comment]
Hopefully. I have to sort out the docker image first, but once that is done I just need to rebase my changes on top of the most recent master and update the docker image the script point to.

**Comment by joshuata** [comment]
I'm opening a new PR that should be much cleaner

**Pull request closed without merging**
