### PR TITLE
Fix storage with SMT arrays

### PR DESCRIPTION
**Pull request by norhh**

### CODE REVIEW

**Comment by b-mueller** [comment]
I tested this with some variants of the example in #1095 and it worked. @JoranHonig anything that needs changing?

**Comment by b-mueller** [comment]
@norhh for some reason this still gives me false positives on [wallet_01_ok.sol](https://github.com/SmartContractSecurity/SWC-registry/blob/master/test_cases/solidity/unprotected_critical_functions/wallet_01_ok/wallet_01_ok.sol):

```
$ qmyth wallet_01_ok.json
==== Unprotected Ether Withdrawal ====
SWC ID: 105
Severity: High
Contract: MAIN
Function name: withdraw(uint256)
PC address: 374
Estimated Gas Usage: 768 - 1239
Anyone can withdraw ETH from the contract account.
Arbitrary senders other than the contract creator can withdraw ETH from the contract account without previously having sent an equivalent amount of ETH to it. This is likely to be a vulnerability.
--------------------
Transaction Sequence:

Caller: [CREATOR], data: [CONTRACT CREATION], value: 0x0
Caller: [SOMEGUY], data: 0xd0e30db0, value: 0x1
Caller: [ATTACKER], data: 0x2e1a7d4d0000000000000000000000000000000000000000000000000000000000000001, value: 0x0

==== Unprotected Ether Withdrawal ====
SWC ID: 105
Severity: High
Contract: MAIN
Function name: refund()
PC address: 776
Estimated Gas Usage: 724 - 1195
Anyone can withdraw ETH from the contract account.
Arbitrary senders other than the contract creator can withdraw ETH from the contract account without previously having sent an equivalent amount of ETH to it. This is likely to be a vulnerability.
--------------------
Transaction Sequence:

Caller: [CREATOR], data: [CONTRACT CREATION], value: 0x0
Caller: [SOMEGUY], data: 0xd0e30db0, value: 0x1
Caller: [ATTACKER], data: 0x590e1ae3, value: 0x0

==== Exception State ====
SWC ID: 110
Severity: Low
Contract: MAIN
Function name: deposit()
PC address: 1008
Estimated Gas Usage: 1177 - 1652
A reachable exception has been detected.
It is possible to trigger an exception (opcode 0xfe). Exceptions can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. Note that explicit `assert()` should only be used to check invariants. Use `require()` for regular input checking.
--------------------
Transaction Sequence:

Caller: [CREATOR], data: [CONTRACT CREATION], value: 0x0
Caller: [SOMEGUY], data: 0x2e1a7d4d, value: 0x0
Caller: [ATTACKER], data: 0xd0e30db0, value: 0x0
```

**Comment by norhh** [comment]
@b-mueller It should be fixed now.

**Comment by b-mueller** [comment]
Yep, looking good! Don't forget the black formatting hahaha

**Pull request merged**
