### PR TITLE
Allow missing solc

### PR DESCRIPTION
**Pull request by mrx23dot**
Will download itself if missing.

myth analyze simple.sol --solv v0.5.16
The analysis was completed successfully. No issues were detected.

### CODE REVIEW

**Comment by norhh** [comment]
@mrx23dot can you sign the CLA and rerun the ci-test, since for was some server error from sonarQube.

**Comment by mrx23dot** [comment]
Hi, I signed the cla, not sure what's up with the CI test, fails on manual running at https://app.circleci.com
```
ERROR: Error during SonarScanner execution
org.sonarsource.scanner.api.internal.ScannerException: Unable to execute SonarScanner analysis
```
second commit didn't trigger a new test on github.

**Comment by norhh** [comment]
@mrx23dot are you sure you signed the CLA? It doesn't seem to be reflected by the CLAassistant.

**Comment by mrx23dot** [comment]
2022-01-10 13_50_28-CLA assistant - Opera

**Comment by norhh** [comment]
I can't seem to re-run the ci, can you make a new commit with some small changes to the comment `allow missing solc, will download instead`.

**Comment by mrx23dot** [comment]
Done, if that doesn't work you can just copy my changes locally.

**Review by norhh — APPROVED** [review]
I'll be force merging this. Thanks for the contribution!

**Pull request merged**
